// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectGameDir() {
  return window['go']['main']['App']['DetectGameDir']();
}

export function GeneratePatch(arg1) {
  return window['go']['main']['App']['GeneratePatch'](arg1);
}

export function OpenPatchFolder() {
  return window['go']['main']['App']['OpenPatchFolder']();
}

export function PickGameDir() {
  return window['go']['main']['App']['PickGameDir']();
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}
