// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DetectPaths():Promise<main.PathDefaultsDTO>;

export function GeneratePatch(arg1:Array<string>):Promise<main.GenerateResultDTO>;

export function OpenPatchFolder():Promise<void>;

export function PickOutputRoot(arg1:string):Promise<string>;

export function PickScanRoot(arg1:string):Promise<string>;

export function Scan(arg1:string,arg2:string):Promise<main.ScanResultDTO>;
