// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectPaths() {
  return window['go']['main']['App']['DetectPaths']();
}

export function GeneratePatch(arg1) {
  return window['go']['main']['App']['GeneratePatch'](arg1);
}

export function OpenPatchFolder() {
  return window['go']['main']['App']['OpenPatchFolder']();
}

export function PickOutputRoot(arg1) {
  return window['go']['main']['App']['PickOutputRoot'](arg1);
}

export function PickScanRoot(arg1) {
  return window['go']['main']['App']['PickScanRoot'](arg1);
}

export function Scan(arg1, arg2) {
  return window['go']['main']['App']['Scan'](arg1, arg2);
}
