// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DetectGameDir():Promise<string>;

export function GeneratePatch(arg1:Array<string>):Promise<main.GenerateResultDTO>;

export function OpenPatchFolder():Promise<void>;

export function PickGameDir():Promise<string>;

export function Scan(arg1:string):Promise<main.ScanResultDTO>;
